package com.example.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ZH("zh", "中文", "简体中文"),
    EN("en", "English", "English"),
    JA("ja", "日本語", "日本語"),
    FR("fr", "Français", "Français"),
    ES("es", "Español", "Español")
}

object Localization {
    private val translations = mapOf(
        AppLanguage.ZH to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "搜索...",
            "widget_settings" to "小组件设置",
            "add_note" to "新增记事",
            "no_notes" to "无记事",
            "write_first_idea" to "写下您的第一条想法",
            "click_to_start" to "点击右下角按钮，立即开始记录吧！",
            "no_notes_found" to "未找到相关记事",
            "try_different_keyword" to "请尝试更换关键词搜索",
            "pinned" to "已固定",
            "others" to "其他记事",
            "untitled" to "无标题",
            "empty_content" to "空内容",
            "widget_customization" to "小组件自定义",
            "widget_customization_desc" to "在此调节桌面小组件的背景透明度，小组件将实时匹配系统浅色/深色主题并同步更新色系。",
            "opacity" to "不透明度",
            "desktop_preview" to "桌面预览 (当前主题下)",
            "realtime_preview_title" to "💡 实时预览示例",
            "realtime_preview_desc" to "这就是您的小组件在桌面的完美质感效果...",
            "done" to "完成",
            "loading" to "加载中...",
            "new_note" to "新建记事",
            "edit_note" to "编辑记事",
            "save" to "保存",
            "back" to "返回",
            "delete" to "删除",
            "pin" to "固定",
            "unpin" to "取消固定",
            "color_label" to "配色:",
            "default_color" to "默认",
            "color_sage" to "薄荷绿",
            "color_sky" to "天空蓝",
            "color_lavender" to "薰衣草",
            "color_rose" to "蔷薇粉",
            "color_peach" to "温暖橙",
            "color_slate" to "石板灰",
            "edit" to "编辑",
            "preview" to "预览",
            "unsaved_changes_title" to "未保存的更改",
            "unsaved_changes_desc" to "你有未保存的内容，确定要离开吗？",
            "leave" to "离开",
            "markdown_preview_empty" to "在此显示 Markdown 预览",
            "no_content_preview" to "无具体内容可预览",
            "note_title_placeholder" to "记事标题",
            "note_content_placeholder" to "使用 Markdown 写下您的灵感想法...",
            "language" to "语言",
            "widget_empty_text" to "暂无内容，点击上方 + 新增",
            "delete_confirm" to "确定要删除这条记事吗？",
            "cancel" to "取消",
            "format_heading" to "标题",
            "format_bold" to "加粗",
            "format_italic" to "斜体",
            "format_code" to "代码行",
            "format_quote" to "引用",
            "format_rule" to "分割线",
            "format_codeblock" to "代码块",
            "settings" to "设置",
            "webdav_settings" to "WebDAV 云备份",
            "webdav_url" to "WebDAV 服务器地址",
            "webdav_port" to "服务器端口",
            "webdav_username" to "用户名",
            "webdav_password" to "密码 / 软件授权码",
            "webdav_path" to "备份目录路径 (如 /backup/notes)",
            "backup_now" to "立即备份到云端",
            "restore_now" to "从云端恢复数据",
            "backup_success" to "备份成功",
            "backup_failed" to "备份失败，请检查配置或网络",
            "restore_success" to "恢复成功，数据已成功导入",
            "restore_failed" to "恢复失败，云端未找到备份或连接失败",
            "theme" to "界面主题",
            "theme_light" to "浅色模式",
            "theme_dark" to "深色模式",
            "theme_system" to "跟随系统",
            "stt_engine" to "语音识别引擎",
            "stt_native" to "系统原生",
            "stt_vosk" to "Vosk (离线)",
            "webdav_connecting" to "正在连接云端...",
            "webdav_empty_credentials" to "请先填写完整的 WebDAV 配置",
            "auto_backup_desc" to "记事保存时将在后台自动备份至云端",
            "delete_note_desc" to "确定要删除这条记事吗？删除后将无法恢复。",
            "current_one_column" to "当前: 一列",
            "current_two_columns" to "当前: 两列",
            "auto_assign_topic" to "一键智能分配主题",
            "topic_work" to "工作/代码",
            "topic_plan" to "计划/待办",
            "topic_shopping" to "购物",
            "topic_idea" to "灵感/点子",
            "topic_love" to "情感/纪念日",
            "topic_finance" to "财务/理财",
            "topic_study" to "学习",
            "topic_default" to "默认",
            "task_progress" to "任务进度:",
            "pin_note" to "固定记事",
            "unpin_note" to "取消固定",
            "storage_permission_denied" to "需要存储权限以保存图片",
            "auto_assign_topic_success" to "一键智能分配主题完成 (更新了 %d 条记事)",
            "note_topic" to "记事主题",
            "about_title" to "关于 & 使用指南",
            "about_app_desc" to "一款基于 Jetpack Compose 构建的现代极简 Markdown 记事本，提供优雅的瀑布流视图、智能主题分类、快捷丰富的桌面组件，为您打造最纯粹、高效的灵感记录体验。",
            "about_features_title" to "💡 核心功能速览",
            "about_feature_1_title" to "📝 Markdown 快捷编辑",
            "about_feature_1_desc" to "✨ 快捷工具栏：一键插入标题、加粗、引用、代码块，告别繁琐语法。\n✨ 实时预览：点击底部切换按钮，瞬间查看精美的 Markdown 渲染效果。",
            "about_feature_2_title" to "🎨 个性配色与瀑布流",
            "about_feature_2_desc" to "✨ 护眼卡片：提供多款精心调校的高颜值浅色与暗色笔记配色。\n✨ 智能归类：支持一键智能分配主题，应用自动记忆您的折叠习惯。\n✨ 优雅排版：双列瀑布流布局让长短不同的记事错落有致，美观实用。",
            "about_feature_3_title" to "🧩 桌面小组件",
            "about_feature_3_desc" to "✨ 完美百搭：支持 0% - 100% 自由调节背景透明度，自然融入任何桌面壁纸。\n✨ 快捷入口：点击小组件右上角按钮，瞬间直达新建记事页面，灵感不掉线。",
            "about_feature_4_title" to "🚀 效率倍增工具",
            "about_feature_4_desc" to "✨ 多格式导出：支持一键将笔记生成为长图，或导出为 Word (.doc) 随时分享。\n✨ 自定义模板：长按主页“新建”按钮唤出模板，随时复用您的专属记录格式。\n✨ 全场景新建：支持长按桌面图标、下拉控制中心磁铁，或从外部应用分享文本快捷新建记事。",
            "about_feature_5_title" to "☁️ WebDAV 云端备份",
            "about_feature_5_desc" to "✨ 数据无忧：支持坚果云、Nextcloud 等标准 WebDAV，随时双向备份防丢失。\n✨ 温馨提示：若使用坚果云，请在网页版“安全选项”中生成【应用密码】作为密码填入，切勿直接使用登录密码。",
            "manage_templates_title" to "管理自定义模板",
            "manage_templates_add" to "添加模板",
            "manage_templates_edit" to "编辑模板",
            "manage_templates_name" to "模板名称",
            "manage_templates_content" to "模板内容 (Markdown)",
            "settings_port_hint" to "例如：8080 (选填)",
            "webdav_url_hint" to "https://dav.jianguoyun.com/dav/",
            "webdav_username_hint" to "your_email@example.com",
            "webdav_path_hint" to "/backup/notes",
            "settings_manage_templates_desc" to "添加或修改内置记事模板",
            "settings_about_desc" to "详细了解墨韵记事各项配置与备份指南",
            "settings_view" to "查看",
            "edit_note_image_fail" to "生成图片失败",
            "edit_note_settings_title" to "记事设置",
            "edit_note_color_title" to "记事颜色",
            "edit_note_pin_title" to "置顶记事",
            "edit_note_widget_title" to "在小组件中显示",
            "edit_note_share_title" to "分享",
            "edit_note_share_text" to "分享文本",
            "edit_note_share_image" to "分享图片",
            "edit_note_save_image" to "保存图片",
            "edit_note_export_word" to "导出Word",
            "edit_note_share_fail" to "分享失败",
            "edit_note_image_saved" to "图片已保存至相册",
            "edit_note_save_fail" to "保存失败",
            "edit_note_save_error" to "保存出错: %s"
        ),
        AppLanguage.EN to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "Search...",
            "widget_settings" to "Widget Settings",
            "add_note" to "Add Note",
            "no_notes" to "No Notes",
            "write_first_idea" to "Write down your first idea",
            "click_to_start" to "Click the bottom right button to start recording!",
            "no_notes_found" to "No matching notes found",
            "try_different_keyword" to "Please try a different keyword",
            "pinned" to "Pinned",
            "others" to "Other Notes",
            "untitled" to "Untitled",
            "empty_content" to "Empty Content",
            "widget_customization" to "Widget Customization",
            "widget_customization_desc" to "Adjust the transparency of the home screen widget here. It will match light/dark themes and update in real-time.",
            "opacity" to "Opacity",
            "desktop_preview" to "Desktop Preview (Under current theme)",
            "realtime_preview_title" to "💡 Real-time Preview",
            "realtime_preview_desc" to "This is exactly how your widget looks on the desktop...",
            "done" to "Done",
            "loading" to "Loading...",
            "new_note" to "New Note",
            "edit_note" to "Edit Note",
            "save" to "Save",
            "back" to "Back",
            "delete" to "Delete",
            "pin" to "Pin",
            "unpin" to "Unpin",
            "color_label" to "Color:",
            "default_color" to "Default",
            "color_sage" to "Sage",
            "color_sky" to "Sky",
            "color_lavender" to "Lavender",
            "color_rose" to "Rose",
            "color_peach" to "Peach",
            "color_slate" to "Slate",
            "edit" to "Edit",
            "preview" to "Preview",
            "unsaved_changes_title" to "Unsaved Changes",
            "unsaved_changes_desc" to "You have unsaved changes. Are you sure you want to leave?",
            "leave" to "Leave",
            "markdown_preview_empty" to "Markdown preview will be displayed here",
            "no_content_preview" to "No content to preview",
            "note_title_placeholder" to "Note Title",
            "note_content_placeholder" to "Use Markdown to write down your inspiration...",
            "language" to "Language",
            "widget_empty_text" to "No notes, tap + above to add",
            "delete_confirm" to "Are you sure you want to delete this note?",
            "cancel" to "Cancel",
            "format_heading" to "Heading",
            "format_bold" to "Bold",
            "format_italic" to "Italic",
            "format_code" to "Inline Code",
            "format_quote" to "Blockquote",
            "format_rule" to "Horizontal Rule",
            "format_codeblock" to "Code Block",
            "settings" to "Settings",
            "webdav_settings" to "WebDAV Cloud Backup",
            "webdav_url" to "WebDAV Server URL",
            "webdav_port" to "Server Port",
            "webdav_username" to "Username",
            "webdav_password" to "Password / App Password",
            "webdav_path" to "Backup Path (e.g. /backup/notes)",
            "backup_now" to "Backup to Cloud Now",
            "restore_now" to "Restore from Cloud",
            "backup_success" to "Backup successful",
            "backup_failed" to "Backup failed, check config or network",
            "restore_success" to "Restore successful, data imported",
            "restore_failed" to "Restore failed, no backup found or connection error",
            "theme" to "App Theme",
            "theme_light" to "Light Mode",
            "theme_dark" to "Dark Mode",
            "theme_system" to "Follow System",
            "stt_engine" to "Speech Engine",
            "stt_native" to "System",
            "stt_vosk" to "Vosk (Offline)",
            "webdav_connecting" to "Connecting to Cloud...",
            "webdav_empty_credentials" to "Please configure WebDAV first",
            "auto_backup_desc" to "Auto-backups to cloud on save in the background",
            "delete_note_desc" to "Are you sure you want to delete this note? It cannot be recovered.",
            "current_one_column" to "Current: 1 Column",
            "current_two_columns" to "Current: 2 Columns",
            "auto_assign_topic" to "Auto-assign Topics",
            "topic_work" to "Work/Code",
            "topic_plan" to "Plan/Todo",
            "topic_shopping" to "Shopping",
            "topic_idea" to "Idea/Inspiration",
            "topic_love" to "Love/Anniversary",
            "topic_finance" to "Finance/Money",
            "topic_study" to "Study",
            "topic_default" to "Default",
            "task_progress" to "Task Progress:",
            "pin_note" to "Pin Note",
            "unpin_note" to "Unpin Note",
            "storage_permission_denied" to "Storage permission is required to save image",
            "auto_assign_topic_success" to "Auto-assign completed (updated %d notes)",
            "note_topic" to "Note Topic",
            "about_title" to "About & Guide",
            "about_app_desc" to "A modern, minimalist Markdown notepad built with Jetpack Compose. Features elegant waterfall layout, smart topic categorization, and rich desktop widgets, providing the purest and most efficient inspiration recording experience.",
            "about_features_title" to "💡 Core Features",
            "about_feature_1_title" to "📝 Quick Markdown Editing",
            "about_feature_1_desc" to "✨ Quick toolbar: One-click insert titles, bold, quotes, code blocks, say goodbye to tedious syntax.\n✨ Real-time preview: Click the bottom switch button to instantly view beautiful Markdown rendering.",
            "about_feature_2_title" to "🎨 Custom Colors & Waterfall Layout",
            "about_feature_2_desc" to "✨ Eye-care cards: Provides a variety of carefully tuned high-value light and dark note color schemes.\n✨ Smart categorization: Supports one-click smart topic assignment, the app automatically remembers your folding habits.\n✨ Elegant layout: Two-column waterfall layout makes notes of different lengths well-arranged, beautiful and practical.",
            "about_feature_3_title" to "🧩 Desktop Widgets",
            "about_feature_3_desc" to "✨ Perfect match: Supports 0% - 100% free adjustment of background transparency, naturally blending into any desktop wallpaper.\n✨ Quick access: Click the top right button of the widget to instantly jump to the new note page, inspiration won't drop.",
            "about_feature_4_title" to "🚀 Efficiency Tools",
            "about_feature_4_desc" to "✨ Multi-format export: Supports one-click generating long images of notes, or exporting to Word (.doc) to share at any time.\n✨ Custom templates: Long press the 'New' button on the homepage to call out templates, reuse your exclusive recording format at any time.\n✨ Create anywhere: Support long pressing the desktop icon, pulling down the control center tile, or sharing text from external apps to quickly create notes.",
            "about_feature_5_title" to "☁️ WebDAV Cloud Backup",
            "about_feature_5_desc" to "✨ Data safety: Supports standard WebDAV like Nutstore, Nextcloud, two-way backup at any time to prevent loss.\n✨ Reminder: If using Nutstore, please generate an [App Password] in the 'Security Options' of the web version to fill in, do not use the login password directly.",
            "manage_templates_title" to "Manage Custom Templates",
            "manage_templates_add" to "Add Template",
            "manage_templates_edit" to "Edit Template",
            "manage_templates_name" to "Template Name",
            "manage_templates_content" to "Template Content (Markdown)",
            "settings_port_hint" to "e.g. 8080 (Optional)",
            "webdav_url_hint" to "https://dav.example.com/dav/",
            "webdav_username_hint" to "your_email@example.com",
            "webdav_path_hint" to "/backup/notes",
            "settings_manage_templates_desc" to "Add or edit built-in note templates",
            "settings_about_desc" to "Learn more about configurations and backup guides",
            "settings_view" to "View",
            "edit_note_image_fail" to "Failed to generate image",
            "edit_note_settings_title" to "Note Settings",
            "edit_note_color_title" to "Note Color",
            "edit_note_pin_title" to "Pin Note",
            "edit_note_widget_title" to "Show in Widget",
            "edit_note_share_title" to "Share",
            "edit_note_share_text" to "Share Text",
            "edit_note_share_image" to "Share Image",
            "edit_note_save_image" to "Save Image",
            "edit_note_export_word" to "Export Word",
            "edit_note_share_fail" to "Failed to share",
            "edit_note_image_saved" to "Image saved to gallery",
            "edit_note_save_fail" to "Failed to save",
            "edit_note_save_error" to "Save error: %s"
        ),
        AppLanguage.JA to mapOf(
            "theme" to "アプリのテーマ",
            "theme_light" to "ライトモード",
            "theme_dark" to "ダークモード",
            "theme_system" to "システムに従う",
            "stt_engine" to "Speech Engine",
            "stt_native" to "System",
            "stt_vosk" to "Vosk (Offline)",
            "webdav_connecting" to "クラウドに接続しています...",
            "webdav_empty_credentials" to "まずWebDAVを設定してください",
            "auto_backup_desc" to "保存時にバックグラウンドで自動的にクラウドにバックアップします",
            "app_title" to "XiNote",
            "search_placeholder" to "検索...",
            "widget_settings" to "ウィジェット設定",
            "add_note" to "メモを追加",
            "no_notes" to "メモがありません",
            "write_first_idea" to "最初のアイデアを書き留めましょう",
            "click_to_start" to "右下のボタンをタップして、記録を始めましょう！",
            "no_notes_found" to "一致するメモが見つかりません",
            "try_different_keyword" to "別のキーワードで検索してみてください",
            "pinned" to "固定済み",
            "others" to "その他のメモ",
            "untitled" to "無題",
            "empty_content" to "内容なし",
            "widget_customization" to "ウィジェットのカスタマイズ",
            "widget_customization_desc" to "ここでホーム画面ウィジェットの透明度を調整します。システムテーマにリアルタイムで連動します。",
            "opacity" to "不透明度",
            "desktop_preview" to "デスクトッププレビュー (現在のテーマ)",
            "realtime_preview_title" to "💡 リアルタイムプレビュー",
            "realtime_preview_desc" to "これがデスクトップ上のウィジェットの見た目です...",
            "done" to "完了",
            "loading" to "読み込み中...",
            "new_note" to "新しいメモ",
            "edit_note" to "メモを編集",
            "save" to "保存",
            "back" to "戻る",
            "delete" to "削除",
            "pin" to "固定",
            "unpin" to "固定解除",
            "color_label" to "配色:",
            "default_color" to "デフォルト",
            "color_sage" to "セージグリーン",
            "color_sky" to "スカイブルー",
            "color_lavender" to "ラベンダー",
            "color_rose" to "ローズピンク",
            "color_peach" to "ピーチオレンジ",
            "color_slate" to "スレートグレー",
            "edit" to "編集",
            "preview" to "プレビュー",
            "unsaved_changes_title" to "保存されていない変更",
            "unsaved_changes_desc" to "保存されていない変更があります。本当に終了しますか？",
            "leave" to "終了する",
            "markdown_preview_empty" to "ここにMarkdownプレビューが表示されます",
            "no_content_preview" to "プレビューするコンテンツがありません",
            "note_title_placeholder" to "メモのタイトル",
            "note_content_placeholder" to "Markdownを使って、あなたのインスピレーションを書き留めてください...",
            "language" to "言語設定",
            "widget_empty_text" to "メモがありません。上の+で追加",
            "delete_confirm" to "このメモを削除してもよろしいですか？",
            "cancel" to "キャンセル",
            "format_heading" to "見出し",
            "format_bold" to "太字",
            "format_italic" to "斜体",
            "format_code" to "インラインコード",
            "format_quote" to "引用",
            "format_rule" to "水平線",
            "format_codeblock" to "コードブロック",
            "settings" to "設定",
            "webdav_settings" to "WebDAV クラウドバックアップ",
            "webdav_url" to "WebDAV サーバーURL",
            "webdav_port" to "サーバーポート",
            "webdav_username" to "ユーザー名",
            "webdav_password" to "パスワード / アプリパスワード",
            "webdav_path" to "バックアップパス (例: /backup/notes)",
            "backup_now" to "今すぐクラウドにバックアップ",
            "restore_now" to "クラウドから復元",
            "backup_success" to "バックアップ成功",
            "backup_failed" to "バックアップ失敗。設定またはネットワークを確認してください",
            "restore_success" to "復元成功。データをインポートしました",
            "delete_note_desc" to "このメモを削除してもよろしいですか？削除後は復元できません。",
            "current_one_column" to "現在: 1列",
            "current_two_columns" to "現在: 2列",
            "auto_assign_topic" to "トピックの自動割り当て",
            "topic_work" to "仕事/コード",
            "topic_plan" to "計画/ToDo",
            "topic_shopping" to "ショッピング",
            "topic_idea" to "アイデア/インスピレーション",
            "topic_love" to "恋愛/記念日",
            "topic_finance" to "財務/お金",
            "topic_study" to "学習",
            "topic_default" to "デフォルト",
            "task_progress" to "タスクの進捗:",
            "pin_note" to "メモを固定",
            "unpin_note" to "固定解除",
            "storage_permission_denied" to "画像を保存するにはストレージ権限が必要です",
            "auto_assign_topic_success" to "トピックの自動割り当てが完了しました (%d 件更新)",
            "note_topic" to "メモのトピック",
            "about_title" to "について & ガイド",
            "about_app_desc" to "Jetpack Composeで構築されたモダンでミニマルなMarkdownメモ帳。エレガントなウォーターフォールレイアウト、スマートなトピック分類、豊富なデスクトップウィジェットを備え、最も純粋で効率的なインスピレーションの記録体験を提供します。",
            "about_features_title" to "💡 コア機能",
            "about_feature_1_title" to "📝 クイックMarkdown編集",
            "about_feature_1_desc" to "✨ クイックツールバー：タイトル、太字、引用、コードブロックをワンクリックで挿入し、面倒な構文に別れを告げます。\n✨ リアルタイムプレビュー：下部の切り替えボタンをクリックして、美しいMarkdownレンダリングを即座に表示します。",
            "about_feature_2_title" to "🎨 カスタムカラー＆ウォーターフォールレイアウト",
            "about_feature_2_desc" to "✨ アイケアカード：慎重に調整された高価値のライトおよびダークメモカラーのテーマを多数提供します。\n✨ スマート分類：ワンクリックのスマートトピック割り当てをサポートし、アプリは折りたたみの習慣を自動的に記憶します。\n✨ エレガントなレイアウト：2列のウォーターフォールレイアウトにより、長さの異なるメモが整理され、美しく実用的です。",
            "about_feature_3_title" to "🧩 デスクトップウィジェット",
            "about_feature_3_desc" to "✨ 完璧な一致：背景の透明度の0％〜100％の自由な調整をサポートし、デスクトップの壁紙に自然に溶け込みます。\n✨ クイックアクセス：ウィジェットの右上隅にあるボタンをクリックすると、即座に新しいメモページにジャンプし、インスピレーションを逃しません。",
            "about_feature_4_title" to "🚀 効率向上ツール",
            "about_feature_4_desc" to "✨ マルチフォーマットのエクスポート：ワンクリックでメモの長い画像を生成したり、Word（.doc）にエクスポートしていつでも共有したりできます。\n✨ カスタムテンプレート：ホームページの「新規」ボタンを長押ししてテンプレートを呼び出し、いつでも専用の記録フォーマットを再利用できます。\n✨ どこでも作成：デスクトップアイコンの長押し、コントロールセンターのタイルのプルダウン、または外部アプリからのテキストの共有をサポートして、メモをすばやく作成します。",
            "about_feature_5_title" to "☁️ WebDAV クラウドバックアップ",
            "about_feature_5_desc" to "✨ データの安全性：Nutstore、Nextcloudなどの標準WebDAVをサポートし、いつでも双方向のバックアップを行って紛失を防ぎます。\n✨ リマインダー：Nutstoreを使用する場合は、Webバージョンの「セキュリティオプション」で「アプリパスワード」を生成して入力してください。ログインパスワードを直接使用しないでください。",
            "manage_templates_title" to "カスタムテンプレートの管理",
            "manage_templates_add" to "テンプレートを追加",
            "manage_templates_edit" to "テンプレートを編集",
            "manage_templates_name" to "テンプレート名",
            "manage_templates_content" to "テンプレートコンテンツ (Markdown)",
            "settings_port_hint" to "例: 8080 (任意)",
            "webdav_url_hint" to "https://dav.example.com/dav/",
            "webdav_username_hint" to "your_email@example.com",
            "webdav_path_hint" to "/backup/notes",
            "settings_manage_templates_desc" to "組み込みのメモテンプレートを追加または編集する",
            "settings_about_desc" to "構成とバックアップガイドの詳細",
            "settings_view" to "見る",
            "edit_note_image_fail" to "画像の生成に失敗しました",
            "edit_note_settings_title" to "メモの設定",
            "edit_note_color_title" to "メモの色",
            "edit_note_pin_title" to "メモを固定",
            "edit_note_widget_title" to "ウィジェットに表示",
            "edit_note_share_title" to "共有",
            "edit_note_share_text" to "テキストを共有",
            "edit_note_share_image" to "画像を共有",
            "edit_note_save_image" to "画像を保存",
            "edit_note_export_word" to "Wordにエクスポート",
            "edit_note_share_fail" to "共有に失敗しました",
            "edit_note_image_saved" to "画像がギャラリーに保存されました",
            "edit_note_save_fail" to "保存に失敗しました",
            "edit_note_save_error" to "保存エラー: %s"
        ),
        AppLanguage.FR to mapOf(
            "theme" to "Thème de l'application",
            "theme_light" to "Mode Clair",
            "theme_dark" to "Mode Sombre",
            "theme_system" to "Suivre le Système",
            "stt_engine" to "Speech Engine",
            "stt_native" to "System",
            "stt_vosk" to "Vosk (Offline)",
            "webdav_connecting" to "Connexion au Cloud...",
            "webdav_empty_credentials" to "Veuillez d'abord configurer WebDAV",
            "auto_backup_desc" to "Sauvegarde automatique sur le cloud en arrière-plan",
            "app_title" to "XiNote",
            "search_placeholder" to "Rechercher...",
            "widget_settings" to "Paramètres du widget",
            "add_note" to "Ajouter une note",
            "no_notes" to "Aucune note",
            "write_first_idea" to "Écrivez votre première idée",
            "click_to_start" to "Cliquez sur le bouton en bas à droite pour commencer !",
            "no_notes_found" to "Aucune note correspondante",
            "try_different_keyword" to "Veuillez essayer un autre mot-clé",
            "pinned" to "Épinglé",
            "others" to "Autres notes",
            "untitled" to "Sans titre",
            "empty_content" to "Contenu vide",
            "widget_customization" to "Personnalisation du widget",
            "widget_customization_desc" to "Ajustez ici la transparence du widget d'écran d'accueil. Il s'adaptera en temps réel aux thèmes clair/sombre.",
            "opacity" to "Opacité",
            "desktop_preview" to "Aperçu du bureau (Sous le thème actuel)",
            "realtime_preview_title" to "💡 Aperçu en temps réel",
            "realtime_preview_desc" to "C'est exactement à quoi ressemble votre widget sur le bureau...",
            "done" to "Terminé",
            "loading" to "Chargement...",
            "new_note" to "Nouvelle note",
            "edit_note" to "Modifier la note",
            "save" to "Enregistrer",
            "back" to "Retour",
            "delete" to "Supprimer",
            "pin" to "Épingler",
            "unpin" to "Déséplingler",
            "color_label" to "Couleur:",
            "default_color" to "Défaut",
            "color_sage" to "Sauge",
            "color_sky" to "Ciel",
            "color_lavender" to "Lavande",
            "color_rose" to "Rose",
            "color_peach" to "Pêche",
            "color_slate" to "Ardoise",
            "edit" to "Édition",
            "preview" to "Aperçu",
            "unsaved_changes_title" to "Modifications non enregistrées",
            "unsaved_changes_desc" to "Vous avez des modifications non enregistrées. Êtes-vous sûr de vouloir quitter ?",
            "leave" to "Quitter",
            "markdown_preview_empty" to "L'aperçu Markdown s'affichera ici",
            "no_content_preview" to "Aucun contenu à prévisualiser",
            "note_title_placeholder" to "Titre de la note",
            "note_content_placeholder" to "Utilisez Markdown pour écrire votre inspiration...",
            "language" to "Langue",
            "widget_empty_text" to "Aucune note, appuyez sur + ci-dessus",
            "delete_confirm" to "Êtes-vous sûr de vouloir supprimer cette note?",
            "cancel" to "Annuler",
            "format_heading" to "Titre",
            "format_bold" to "Gras",
            "format_italic" to "Italique",
            "format_code" to "Code en ligne",
            "format_quote" to "Citation",
            "format_rule" to "Ligne horizontale",
            "format_codeblock" to "Bloc de code",
            "settings" to "Paramètres",
            "webdav_settings" to "Sauvegarde Cloud WebDAV",
            "webdav_url" to "URL du Serveur WebDAV",
            "webdav_port" to "Port du Serveur",
            "webdav_username" to "Nom d'utilisateur",
            "webdav_password" to "Mot de passe / Mot de passe d'application",
            "webdav_path" to "Chemin de sauvegarde (ex. /backup/notes)",
            "backup_now" to "Sauvegarder sur le Cloud Maintenant",
            "restore_now" to "Restaurer depuis le Cloud",
            "backup_success" to "Sauvegarde réussie",
            "backup_failed" to "Échec de la sauvegarde, vérifiez la configuration ou le réseau",
            "restore_success" to "Restauration réussie, données importées",
            "delete_note_desc" to "Êtes-vous sûr de vouloir supprimer cette note ? Elle ne pourra pas être récupérée.",
            "current_one_column" to "Actuel : 1 colonne",
            "current_two_columns" to "Actuel : 2 colonnes",
            "auto_assign_topic" to "Sujets automatiques",
            "topic_work" to "Travail/Code",
            "topic_plan" to "Plan/Tâches",
            "topic_shopping" to "Achats",
            "topic_idea" to "Idée/Inspiration",
            "topic_love" to "Amour/Anniversaire",
            "topic_finance" to "Finance/Argent",
            "topic_study" to "Étude",
            "topic_default" to "Défaut",
            "task_progress" to "Progression des tâches :",
            "pin_note" to "Épingler la note",
            "unpin_note" to "Désépingler la note",
            "storage_permission_denied" to "L'autorisation de stockage est requise pour enregistrer l'image",
            "auto_assign_topic_success" to "Attribution automatique terminée (%d notes mises à jour)",
            "note_topic" to "Sujet de la note",
            "about_title" to "À propos & Guide",
            "about_app_desc" to "Un bloc-notes Markdown moderne et minimaliste construit avec Jetpack Compose. Dispose d'une élégante disposition en cascade, d'une catégorisation intelligente des sujets et de riches widgets de bureau, offrant l'expérience d'enregistrement d'inspiration la plus pure et la plus efficace.",
            "about_features_title" to "💡 Fonctionnalités principales",
            "about_feature_1_title" to "📝 Édition rapide de Markdown",
            "about_feature_1_desc" to "✨ Barre d'outils rapide : un clic pour insérer des titres, du gras, des citations, des blocs de code, dites adieu à la syntaxe fastidieuse.\n✨ Aperçu en temps réel : cliquez sur le bouton de bascule en bas pour afficher instantanément le magnifique rendu Markdown.",
            "about_feature_2_title" to "🎨 Couleurs personnalisées & Disposition en cascade",
            "about_feature_2_desc" to "✨ Cartes de soin des yeux : fournit une variété de thèmes de couleurs de notes claires et sombres de grande valeur soigneusement ajustés.\n✨ Catégorisation intelligente : prend en charge l'attribution intelligente des sujets en un clic, l'application se souvient automatiquement de vos habitudes de pliage.\n✨ Disposition élégante : la disposition en cascade à deux colonnes rend les notes de différentes longueurs bien arrangées, belles et pratiques.",
            "about_feature_3_title" to "🧩 Widgets de bureau",
            "about_feature_3_desc" to "✨ Correspondance parfaite : prend en charge un réglage libre de la transparence de l'arrière-plan de 0 % à 100 %, s'intégrant naturellement dans n'importe quel fond d'écran de bureau.\n✨ Accès rapide : cliquez sur le bouton en haut à droite du widget pour accéder instantanément à la nouvelle page de notes, l'inspiration ne tombera pas.",
            "about_feature_4_title" to "🚀 Outils d'efficacité",
            "about_feature_4_desc" to "✨ Exportation multi-format : prend en charge la génération d'images longues de notes en un clic, ou l'exportation vers Word (.doc) pour partager à tout moment.\n✨ Modèles personnalisés : appuyez longuement sur le bouton 'Nouveau' sur la page d'accueil pour appeler des modèles, réutilisez votre format d'enregistrement exclusif à tout moment.\n✨ Créer n'importe où : prend en charge l'appui long sur l'icône du bureau, le menu déroulant de la vignette du centre de contrôle, ou le partage de texte à partir d'applications externes pour créer rapidement des notes.",
            "about_feature_5_title" to "☁️ Sauvegarde WebDAV",
            "about_feature_5_desc" to "✨ Sécurité des données : prend en charge les protocoles WebDAV standard comme Nutstore, Nextcloud, sauvegarde bidirectionnelle à tout moment pour éviter la perte.\n✨ Rappel : si vous utilisez Nutstore, veuillez générer un [Mot de passe d'application] dans les 'Options de sécurité' de la version Web à remplir, n'utilisez pas directement le mot de passe de connexion.",
            "manage_templates_title" to "Gérer les modèles personnalisés",
            "manage_templates_add" to "Ajouter un modèle",
            "manage_templates_edit" to "Modifier le modèle",
            "manage_templates_name" to "Nom du modèle",
            "manage_templates_content" to "Contenu du modèle (Markdown)",
            "settings_port_hint" to "ex. 8080 (Optionnel)",
            "webdav_url_hint" to "https://dav.example.com/dav/",
            "webdav_username_hint" to "your_email@example.com",
            "webdav_path_hint" to "/backup/notes",
            "settings_manage_templates_desc" to "Ajouter ou modifier des modèles de notes intégrés",
            "settings_about_desc" to "En savoir plus sur les configurations et les guides de sauvegarde",
            "settings_view" to "Voir",
            "edit_note_image_fail" to "Échec de la génération de l'image",
            "edit_note_settings_title" to "Paramètres de la note",
            "edit_note_color_title" to "Couleur de la note",
            "edit_note_pin_title" to "Épingler la note",
            "edit_note_widget_title" to "Afficher dans le widget",
            "edit_note_share_title" to "Partager",
            "edit_note_share_text" to "Partager le texte",
            "edit_note_share_image" to "Partager l'image",
            "edit_note_save_image" to "Enregistrer l'image",
            "edit_note_export_word" to "Exporter vers Word",
            "edit_note_share_fail" to "Échec du partage",
            "edit_note_image_saved" to "Image enregistrée dans la galerie",
            "edit_note_save_fail" to "Échec de la sauvegarde",
            "edit_note_save_error" to "Erreur de sauvegarde : %s"
        ),
        AppLanguage.ES to mapOf(
            "theme" to "Tema de la aplicación",
            "theme_light" to "Modo Claro",
            "theme_dark" to "Modo Oscuro",
            "theme_system" to "Seguir Sistema",
            "stt_engine" to "Speech Engine",
            "stt_native" to "System",
            "stt_vosk" to "Vosk (Offline)",
            "webdav_connecting" to "Conectando a la Nube...",
            "webdav_empty_credentials" to "Por favor, configure WebDAV primero",
            "auto_backup_desc" to "Copia de seguridad automática en segundo plano",
            "app_title" to "XiNote",
            "search_placeholder" to "Buscar...",
            "widget_settings" to "Ajustes del widget",
            "add_note" to "Añadir nota",
            "no_notes" to "Sin notas",
            "write_first_idea" to "Escribe tu primera idea",
            "click_to_start" to "¡Haz clic en el botón inferior derecho para comenzar!",
            "no_notes_found" to "No se encontraron notas",
            "try_different_keyword" to "Intente con otra palabra clave",
            "pinned" to "Fijado",
            "others" to "Otras notas",
            "untitled" to "Sin título",
            "empty_content" to "Sin contenido",
            "widget_customization" to "Personalización del widget",
            "widget_customization_desc" to "Ajuste la transparencia del widget de pantalla de inicio aquí. Se adaptará en tiempo real a los temas claro/oscuro.",
            "opacity" to "Opacidad",
            "desktop_preview" to "Vista previa de escritorio (Bajo el tema actual)",
            "realtime_preview_title" to "💡 Vista previa en tiempo real",
            "realtime_preview_desc" to "Así es exactamente como se ve su widget en el escritorio...",
            "done" to "Hecho",
            "loading" to "Cargando...",
            "new_note" to "Nueva nota",
            "edit_note" to "Editar nota",
            "save" to "Guardar",
            "back" to "Atrás",
            "delete" to "Eliminar",
            "pin" to "Fijar",
            "unpin" to "Desfijar",
            "color_label" to "Color:",
            "default_color" to "Por defecto",
            "color_sage" to "Salvia",
            "color_sky" to "Cielo",
            "color_lavender" to "Lavanda",
            "color_rose" to "Rosa",
            "color_peach" to "Melocotón",
            "color_slate" to "Pizarra",
            "edit" to "Editar",
            "preview" to "Vista previa",
            "unsaved_changes_title" to "Cambios no guardados",
            "unsaved_changes_desc" to "Tienes cambios no guardados. ¿Estás seguro de que quieres salir?",
            "leave" to "Salir",
            "markdown_preview_empty" to "La vista previa de Markdown se mostrará aquí",
            "no_content_preview" to "No hay contenido para previsualizar",
            "note_title_placeholder" to "Título de la nota",
            "note_content_placeholder" to "Usa Markdown para escribir tu inspiración...",
            "language" to "Idioma",
            "widget_empty_text" to "No hay notas, toca + arriba para añadir",
            "delete_confirm" to "¿Está seguro de que desea eliminar esta nota?",
            "cancel" to "Cancelar",
            "format_heading" to "Encabezado",
            "format_bold" to "Negrita",
            "format_italic" to "Cursiva",
            "format_code" to "Código en línea",
            "format_quote" to "Cita",
            "format_rule" to "Línea horizontal",
            "format_codeblock" to "Bloque de código",
            "settings" to "Ajustes",
            "webdav_settings" to "Copia de Seguridad en la Nube WebDAV",
            "webdav_url" to "URL del Servidor WebDAV",
            "webdav_port" to "Puerto del Servidor",
            "webdav_username" to "Nombre de usuario",
            "webdav_password" to "Contraseña / Contraseña de aplicación",
            "webdav_path" to "Ruta de copia de seguridad (ej. /backup/notes)",
            "backup_now" to "Hacer Copia de Seguridad Ahora",
            "restore_now" to "Restaurar desde la Nube",
            "backup_success" to "Copia de seguridad exitosa",
            "backup_failed" to "Error en la copia de seguridad, compruebe la configuración o la red",
            "restore_success" to "Restauración exitosa, datos importados",
            "delete_note_desc" to "¿Estás seguro de que quieres eliminar esta nota? No se puede recuperar.",
            "current_one_column" to "Actual: 1 columna",
            "current_two_columns" to "Actual: 2 columnas",
            "auto_assign_topic" to "Asignar temas automáticamente",
            "topic_work" to "Trabajo/Código",
            "topic_plan" to "Plan/Tareas",
            "topic_shopping" to "Compras",
            "topic_idea" to "Idea/Inspiración",
            "topic_love" to "Amor/Aniversario",
            "topic_finance" to "Finanzas/Dinero",
            "topic_study" to "Estudio",
            "topic_default" to "Por defecto",
            "task_progress" to "Progreso de las tareas:",
            "pin_note" to "Fijar nota",
            "unpin_note" to "Desfijar nota",
            "storage_permission_denied" to "Se requiere permiso de almacenamiento para guardar la imagen",
            "auto_assign_topic_success" to "Asignación automática completada (%d notas actualizadas)",
            "note_topic" to "Tema de la nota",
            "about_title" to "Acerca de y Guía",
            "about_app_desc" to "Un bloc de notas Markdown moderno y minimalista construido con Jetpack Compose. Cuenta con un diseño elegante en cascada, categorización inteligente de temas y widgets de escritorio ricos, brindando la experiencia de registro de inspiración más pura y eficiente.",
            "about_features_title" to "💡 Características principales",
            "about_feature_1_title" to "📝 Edición rápida de Markdown",
            "about_feature_1_desc" to "✨ Barra de herramientas rápida: un clic para insertar títulos, negrita, citas, bloques de código, dile adiós a la sintaxis tediosa.\n✨ Vista previa en tiempo real: haz clic en el botón de cambio inferior para ver al instante la hermosa representación de Markdown.",
            "about_feature_2_title" to "🎨 Colores personalizados y Diseño en cascada",
            "about_feature_2_desc" to "✨ Tarjetas de cuidado de los ojos: proporciona una variedad de temas de colores de notas claros y oscuros de alto valor cuidadosamente ajustados.\n✨ Categorización inteligente: admite la asignación inteligente de temas con un solo clic, la aplicación recuerda automáticamente sus hábitos de plegado.\n✨ Diseño elegante: el diseño en cascada de dos columnas hace que las notas de diferentes longitudes estén bien organizadas, hermosas y prácticas.",
            "about_feature_3_title" to "🧩 Widgets de escritorio",
            "about_feature_3_desc" to "✨ Combinación perfecta: admite un ajuste libre de la transparencia del fondo del 0% al 100%, combinándose naturalmente con cualquier fondo de pantalla de escritorio.\n✨ Acceso rápido: haz clic en el botón superior derecho del widget para ir instantáneamente a la página de nueva nota, la inspiración no caerá.",
            "about_feature_4_title" to "🚀 Herramientas de eficiencia",
            "about_feature_4_desc" to "✨ Exportación multiformato: admite generar imágenes largas de notas con un clic, o exportar a Word (.doc) para compartir en cualquier momento.\n✨ Plantillas personalizadas: mantén presionado el botón 'Nuevo' en la página de inicio para llamar a las plantillas, reutiliza tu formato de grabación exclusivo en cualquier momento.\n✨ Crear en cualquier lugar: admite mantener presionado el ícono del escritorio, desplegar el mosaico del centro de control o compartir texto de aplicaciones externas para crear notas rápidamente.",
            "about_feature_5_title" to "☁️ Copia de seguridad en la nube WebDAV",
            "about_feature_5_desc" to "✨ Seguridad de datos: admite protocolos WebDAV estándar como Nutstore, Nextcloud, copia de seguridad bidireccional en cualquier momento para evitar pérdidas.\n✨ Recordatorio: si usas Nutstore, genera una [Contraseña de aplicación] en las 'Opciones de seguridad' de la versión web para completarla, no uses la contraseña de inicio de sesión directamente.",
            "manage_templates_title" to "Administrar plantillas personalizadas",
            "manage_templates_add" to "Añadir plantilla",
            "manage_templates_edit" to "Editar plantilla",
            "manage_templates_name" to "Nombre de la plantilla",
            "manage_templates_content" to "Contenido de la plantilla (Markdown)",
            "settings_port_hint" to "ej. 8080 (Opcional)",
            "webdav_url_hint" to "https://dav.example.com/dav/",
            "webdav_username_hint" to "your_email@example.com",
            "webdav_path_hint" to "/backup/notes",
            "settings_manage_templates_desc" to "Añadir o editar plantillas de notas incorporadas",
            "settings_about_desc" to "Obtén más información sobre las configuraciones y las guías de respaldo",
            "settings_view" to "Ver",
            "edit_note_image_fail" to "Error al generar la imagen",
            "edit_note_settings_title" to "Configuración de notas",
            "edit_note_color_title" to "Color de la nota",
            "edit_note_pin_title" to "Fijar nota",
            "edit_note_widget_title" to "Mostrar en widget",
            "edit_note_share_title" to "Compartir",
            "edit_note_share_text" to "Compartir texto",
            "edit_note_share_image" to "Compartir imagen",
            "edit_note_save_image" to "Guardar imagen",
            "edit_note_export_word" to "Exportar Word",
            "edit_note_share_fail" to "Error al compartir",
            "edit_note_image_saved" to "Imagen guardada en la galería",
            "edit_note_save_fail" to "Error al guardar",
            "edit_note_save_error" to "Error al guardar: %s"
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ZH]?.get(key) ?: key
    }

    fun getColorName(colorKey: String, language: AppLanguage): String {
        val lKey = when (colorKey) {
            "default" -> "default_color"
            "sage" -> "color_sage"
            "sky" -> "color_sky"
            "lavender" -> "color_lavender"
            "rose" -> "color_rose"
            "peach" -> "color_peach"
            "slate" -> "color_slate"
            else -> "default_color"
        }
        return getString(lKey, language)
    }

    fun getTopicName(topicDb: String, language: AppLanguage): String {
        val lKey = when (topicDb) {
            "工作/代码" -> "topic_work"
            "计划/待办" -> "topic_plan"
            "购物" -> "topic_shopping"
            "灵感/点子" -> "topic_idea"
            "情感/纪念日" -> "topic_love"
            "财务/理财" -> "topic_finance"
            "学习" -> "topic_study"
            "默认" -> "topic_default"
            else -> return topicDb
        }
        return getString(lKey, language)
    }
}
