package com.example.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ZH("zh", "中文", "简体中文"),
    EN("en", "English", "English"),
    JA("ja", "日本語", "日本語"),
    FR("fr", "Français", "Français"),
    ES("es", "Español", "Español")
}

object Localization {
    private val translations = mapOf(
        AppLanguage.ZH to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "搜索...",
            "widget_settings" to "小组件设置",
            "add_note" to "新增记事",
            "no_notes" to "无记事",
            "write_first_idea" to "写下您的第一条想法",
            "click_to_start" to "点击右下角按钮，立即开始记录吧！",
            "no_notes_found" to "未找到相关记事",
            "try_different_keyword" to "请尝试更换关键词搜索",
            "pinned" to "已固定",
            "others" to "其他记事",
            "untitled" to "无标题",
            "empty_content" to "空内容",
            "widget_customization" to "小组件自定义",
            "widget_customization_desc" to "在此调节桌面小组件的背景透明度，小组件将实时匹配系统浅色/深色主题并同步更新色系。",
            "opacity" to "不透明度",
            "desktop_preview" to "桌面预览 (当前主题下)",
            "realtime_preview_title" to "💡 实时预览示例",
            "realtime_preview_desc" to "这就是您的小组件在桌面的完美质感效果...",
            "done" to "完成",
            "loading" to "加载中...",
            "new_note" to "新建记事",
            "edit_note" to "编辑记事",
            "save" to "保存",
            "back" to "返回",
            "delete" to "删除",
            "pin" to "固定",
            "unpin" to "取消固定",
            "color_label" to "配色:",
            "default_color" to "默认",
            "color_sage" to "薄荷绿",
            "color_sky" to "天空蓝",
            "color_lavender" to "薰衣草",
            "color_rose" to "蔷薇粉",
            "color_peach" to "温暖橙",
            "color_slate" to "石板灰",
            "edit" to "编辑",
            "preview" to "预览",
            "markdown_preview_empty" to "在此显示 Markdown 预览",
            "no_content_preview" to "无具体内容可预览",
            "note_title_placeholder" to "记事标题",
            "note_content_placeholder" to "使用 Markdown 写下您的灵感想法...",
            "language" to "语言",
            "widget_empty_text" to "暂无内容，点击上方 + 新增",
            "delete_confirm" to "确定要删除这条记事吗？",
            "cancel" to "取消",
            "format_heading" to "标题",
            "format_bold" to "加粗",
            "format_italic" to "斜体",
            "format_code" to "代码行",
            "format_quote" to "引用",
            "format_rule" to "分割线",
            "format_codeblock" to "代码块",
            "settings" to "设置",
            "webdav_settings" to "WebDAV 云备份",
            "webdav_url" to "WebDAV 服务器地址",
            "webdav_username" to "用户名",
            "webdav_password" to "密码 / 软件授权码",
            "webdav_path" to "备份目录路径 (如 /backup/notes)",
            "backup_now" to "立即备份到云端",
            "restore_now" to "从云端恢复数据",
            "backup_success" to "备份成功",
            "backup_failed" to "备份失败，请检查配置或网络",
            "restore_success" to "恢复成功，数据已成功导入",
            "restore_failed" to "恢复失败，云端未找到备份或连接失败",
            "theme" to "界面主题",
            "theme_light" to "浅色模式",
            "theme_dark" to "深色模式",
            "theme_system" to "跟随系统",
            "webdav_connecting" to "正在连接云端...",
            "webdav_empty_credentials" to "请先填写完整的 WebDAV 配置",
            "auto_backup_desc" to "记事保存时将在后台自动备份至云端"
        ),
        AppLanguage.EN to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "Search...",
            "widget_settings" to "Widget Settings",
            "add_note" to "Add Note",
            "no_notes" to "No Notes",
            "write_first_idea" to "Write down your first idea",
            "click_to_start" to "Click the bottom right button to start recording!",
            "no_notes_found" to "No matching notes found",
            "try_different_keyword" to "Please try a different keyword",
            "pinned" to "Pinned",
            "others" to "Other Notes",
            "untitled" to "Untitled",
            "empty_content" to "Empty Content",
            "widget_customization" to "Widget Customization",
            "widget_customization_desc" to "Adjust the transparency of the home screen widget here. It will match light/dark themes and update in real-time.",
            "opacity" to "Opacity",
            "desktop_preview" to "Desktop Preview (Under current theme)",
            "realtime_preview_title" to "💡 Real-time Preview",
            "realtime_preview_desc" to "This is exactly how your widget looks on the desktop...",
            "done" to "Done",
            "loading" to "Loading...",
            "new_note" to "New Note",
            "edit_note" to "Edit Note",
            "save" to "Save",
            "back" to "Back",
            "delete" to "Delete",
            "pin" to "Pin",
            "unpin" to "Unpin",
            "color_label" to "Color:",
            "default_color" to "Default",
            "color_sage" to "Sage",
            "color_sky" to "Sky",
            "color_lavender" to "Lavender",
            "color_rose" to "Rose",
            "color_peach" to "Peach",
            "color_slate" to "Slate",
            "edit" to "Edit",
            "preview" to "Preview",
            "markdown_preview_empty" to "Markdown preview will be displayed here",
            "no_content_preview" to "No content to preview",
            "note_title_placeholder" to "Note Title",
            "note_content_placeholder" to "Use Markdown to write down your inspiration...",
            "language" to "Language",
            "widget_empty_text" to "No notes, tap + above to add",
            "delete_confirm" to "Are you sure you want to delete this note?",
            "cancel" to "Cancel",
            "format_heading" to "Heading",
            "format_bold" to "Bold",
            "format_italic" to "Italic",
            "format_code" to "Inline Code",
            "format_quote" to "Blockquote",
            "format_rule" to "Horizontal Rule",
            "format_codeblock" to "Code Block",
            "settings" to "Settings",
            "webdav_settings" to "WebDAV Cloud Backup",
            "webdav_url" to "WebDAV Server URL",
            "webdav_username" to "Username",
            "webdav_password" to "Password / App Password",
            "webdav_path" to "Backup Path (e.g. /backup/notes)",
            "backup_now" to "Backup to Cloud Now",
            "restore_now" to "Restore from Cloud",
            "backup_success" to "Backup successful",
            "backup_failed" to "Backup failed, check config or network",
            "restore_success" to "Restore successful, data imported",
            "restore_failed" to "Restore failed, no backup found or connection error",
            "theme" to "App Theme",
            "theme_light" to "Light Mode",
            "theme_dark" to "Dark Mode",
            "theme_system" to "Follow System",
            "webdav_connecting" to "Connecting to Cloud...",
            "webdav_empty_credentials" to "Please configure WebDAV first",
            "auto_backup_desc" to "Auto-backups to cloud on save in the background"
        ),
        AppLanguage.JA to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "検索...",
            "widget_settings" to "ウィジェット設定",
            "add_note" to "メモを追加",
            "no_notes" to "メモがありません",
            "write_first_idea" to "最初のアイデアを書き留めましょう",
            "click_to_start" to "右下のボタンをタップして、記録を始めましょう！",
            "no_notes_found" to "一致するメモが見つかりません",
            "try_different_keyword" to "別のキーワードで検索してみてください",
            "pinned" to "固定済み",
            "others" to "その他のメモ",
            "untitled" to "無題",
            "empty_content" to "内容なし",
            "widget_customization" to "ウィジェットのカスタマイズ",
            "widget_customization_desc" to "ここでホーム画面ウィジェットの透明度を調整します。システムテーマにリアルタイムで連動します。",
            "opacity" to "不透明度",
            "desktop_preview" to "デスクトッププレビュー (現在のテーマ)",
            "realtime_preview_title" to "💡 リアルタイムプレビュー",
            "realtime_preview_desc" to "これがデスクトップ上のウィジェットの見た目です...",
            "done" to "完了",
            "loading" to "読み込み中...",
            "new_note" to "新しいメモ",
            "edit_note" to "メモを編集",
            "save" to "保存",
            "back" to "戻る",
            "delete" to "削除",
            "pin" to "固定",
            "unpin" to "固定解除",
            "color_label" to "配色:",
            "default_color" to "デフォルト",
            "color_sage" to "セージグリーン",
            "color_sky" to "スカイブルー",
            "color_lavender" to "ラベンダー",
            "color_rose" to "ローズピンク",
            "color_peach" to "ピーチオレンジ",
            "color_slate" to "スレートグレー",
            "edit" to "編集",
            "preview" to "プレビュー",
            "markdown_preview_empty" to "ここにMarkdownプレビューが表示されます",
            "no_content_preview" to "プレビューするコンテンツがありません",
            "note_title_placeholder" to "メモのタイトル",
            "note_content_placeholder" to "Markdownを使って、あなたのインスピレーションを書き留めてください...",
            "language" to "言語設定",
            "widget_empty_text" to "メモがありません。上の+で追加",
            "delete_confirm" to "このメモを削除してもよろしいですか？",
            "cancel" to "キャンセル",
            "format_heading" to "見出し",
            "format_bold" to "太字",
            "format_italic" to "斜体",
            "format_code" to "インラインコード",
            "format_quote" to "引用",
            "format_rule" to "水平線",
            "format_codeblock" to "コードブロック"
        ),
        AppLanguage.FR to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "Rechercher...",
            "widget_settings" to "Paramètres du widget",
            "add_note" to "Ajouter une note",
            "no_notes" to "Aucune note",
            "write_first_idea" to "Écrivez votre première idée",
            "click_to_start" to "Cliquez sur le bouton en bas à droite pour commencer !",
            "no_notes_found" to "Aucune note correspondante",
            "try_different_keyword" to "Veuillez essayer un autre mot-clé",
            "pinned" to "Épinglé",
            "others" to "Autres notes",
            "untitled" to "Sans titre",
            "empty_content" to "Contenu vide",
            "widget_customization" to "Personnalisation du widget",
            "widget_customization_desc" to "Ajustez ici la transparence du widget d'écran d'accueil. Il s'adaptera en temps réel aux thèmes clair/sombre.",
            "opacity" to "Opacité",
            "desktop_preview" to "Aperçu du bureau (Sous le thème actuel)",
            "realtime_preview_title" to "💡 Aperçu en temps réel",
            "realtime_preview_desc" to "C'est exactement à quoi ressemble votre widget sur le bureau...",
            "done" to "Terminé",
            "loading" to "Chargement...",
            "new_note" to "Nouvelle note",
            "edit_note" to "Modifier la note",
            "save" to "Enregistrer",
            "back" to "Retour",
            "delete" to "Supprimer",
            "pin" to "Épingler",
            "unpin" to "Déséplingler",
            "color_label" to "Couleur:",
            "default_color" to "Défaut",
            "color_sage" to "Sauge",
            "color_sky" to "Ciel",
            "color_lavender" to "Lavande",
            "color_rose" to "Rose",
            "color_peach" to "Pêche",
            "color_slate" to "Ardoise",
            "edit" to "Édition",
            "preview" to "Aperçu",
            "markdown_preview_empty" to "L'aperçu Markdown s'affichera ici",
            "no_content_preview" to "Aucun contenu à prévisualiser",
            "note_title_placeholder" to "Titre de la note",
            "note_content_placeholder" to "Utilisez Markdown pour écrire votre inspiration...",
            "language" to "Langue",
            "widget_empty_text" to "Aucune note, appuyez sur + ci-dessus",
            "delete_confirm" to "Êtes-vous sûr de vouloir supprimer cette note?",
            "cancel" to "Annuler",
            "format_heading" to "Titre",
            "format_bold" to "Gras",
            "format_italic" to "Italique",
            "format_code" to "Code en ligne",
            "format_quote" to "Citation",
            "format_rule" to "Ligne horizontale",
            "format_codeblock" to "Bloc de code"
        ),
        AppLanguage.ES to mapOf(
            "app_title" to "XiNote",
            "search_placeholder" to "Buscar...",
            "widget_settings" to "Ajustes del widget",
            "add_note" to "Añadir nota",
            "no_notes" to "Sin notas",
            "write_first_idea" to "Escribe tu primera idea",
            "click_to_start" to "¡Haz clic en el botón inferior derecho para comenzar!",
            "no_notes_found" to "No se encontraron notas",
            "try_different_keyword" to "Intente con otra palabra clave",
            "pinned" to "Fijado",
            "others" to "Otras notas",
            "untitled" to "Sin título",
            "empty_content" to "Sin contenido",
            "widget_customization" to "Personalización del widget",
            "widget_customization_desc" to "Ajuste la transparencia del widget de pantalla de inicio aquí. Se adaptará en tiempo real a los temas claro/oscuro.",
            "opacity" to "Opacidad",
            "desktop_preview" to "Vista previa de escritorio (Bajo el tema actual)",
            "realtime_preview_title" to "💡 Vista previa en tiempo real",
            "realtime_preview_desc" to "Así es exactamente como se ve su widget en el escritorio...",
            "done" to "Hecho",
            "loading" to "Cargando...",
            "new_note" to "Nueva nota",
            "edit_note" to "Editar nota",
            "save" to "Guardar",
            "back" to "Atrás",
            "delete" to "Eliminar",
            "pin" to "Fijar",
            "unpin" to "Desfijar",
            "color_label" to "Color:",
            "default_color" to "Por defecto",
            "color_sage" to "Salvia",
            "color_sky" to "Cielo",
            "color_lavender" to "Lavanda",
            "color_rose" to "Rosa",
            "color_peach" to "Melocotón",
            "color_slate" to "Pizarra",
            "edit" to "Editar",
            "preview" to "Vista previa",
            "markdown_preview_empty" to "La vista previa de Markdown se mostrará aquí",
            "no_content_preview" to "No hay contenido para previsualizar",
            "note_title_placeholder" to "Título de la nota",
            "note_content_placeholder" to "Usa Markdown para escribir tu inspiración...",
            "language" to "Idioma",
            "widget_empty_text" to "No hay notas, toca + arriba para añadir",
            "delete_confirm" to "¿Está seguro de que desea eliminar esta nota?",
            "cancel" to "Cancelar",
            "format_heading" to "Encabezado",
            "format_bold" to "Negrita",
            "format_italic" to "Cursiva",
            "format_code" to "Código en línea",
            "format_quote" to "Cita",
            "format_rule" to "Línea horizontal",
            "format_codeblock" to "Bloque de código"
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ZH]?.get(key) ?: key
    }

    fun getColorName(colorKey: String, language: AppLanguage): String {
        val lKey = when (colorKey) {
            "default" -> "default_color"
            "sage" -> "color_sage"
            "sky" -> "color_sky"
            "lavender" -> "color_lavender"
            "rose" -> "color_rose"
            "peach" -> "color_peach"
            "slate" -> "color_slate"
            else -> "default_color"
        }
        return getString(lKey, language)
    }
}
